# Generated by Django 4.1.5 on 2023-01-18 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='post',
            new_name='product',
        ),
    ]
