# Generated by Django 4.1.5 on 2023-01-18 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_post_rating_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='product',
            new_name='post',
        ),
    ]
